.TH DEBIAN-VM-BUILDER 1 "Oct 2008"
.SH NAME
debian-vm-builder \- builds virtual machines from the command line
.SH DESCRIPTION
debian-vm-builder is now a wrapper to vmbuilder (part of the
python-vm-builder package) and is only maintained for compatibility wih
previous scripts.  Please see the vmbuilder man page for more information
or run
.B vmbuilder --help
for a full list of options.
.SH SEE ALSO
vmbuilder(1)
